### ISSUE TITLE
Select statement evaluation

### ISSUE THREAD

**Issue by twoxfh** [0x09/sqlite-statement-vtab#2]
Any plans for a select statement evaluation functionality? I am current using the below code to evaluate tables from sqlite_master joined with columns from pragma_table_info so I can dynamically get details about the tables. This can become painful when querying multiple columns in one go with one table scan; eval separates everything by row and column with one separator. I know there are better ways including using sqlite shell, however, I was trying to make it agnostic to the sql client. 

`CREATE VIRTUAL TABLE test USING statement((
  select eval('select min( ' || :column || ') from ' || :table,';')
));`

**Comment by 0x09** [comment]
Hi @twoxfh, can you provide an example of how this would be used? It sounds like this would be better implemented by its own module that could potentially be used together with a statement_vtab, but I'm not sure how something like that would handle multiple columns based on the eval example here.

**Comment by twoxfh** [comment]
@0x09  I should have tried to be more clear. A multi select statement aggregator with the final select being the return of the function. When I see statement(()), it makes me want to chain statements together like :statement((),(),()) the last one being the return. In my case I could wrap ,(select eval create temp table ARG1, create temp table select min max avg columns from sub select columns from SQLite where table, select * from temp table) into

Select * from query_details('select * from table where 1=1')  and get back summary data about the select statement. I'm sure there could be many more uses as well.

The sql would look like:

`
Example Table:
CREATE TABLE house
(
  name TEXT,
  points INTEGER
);
INSERT INTO house VALUES
('Gryffindor', 100),
('Hufflepuff', 90),
('Ravenclaw', 95),
('Slytherin', 80);

Example Function:
1)create table TEMP.t0 AS select * from house where points > 80; -- QUERY ARG1
2)select eval('CREATE table TEMP.t1 AS select count(*) as rows, min(' || replace(sql.cols,';','), min(') || '), max(' || replace(sql.cols,';','), max(') || ') from t0') from (select GROUP_CONCAT(name,';') as cols from (select b.name from sqlite_temp_master a join pragma_table_info(a.name) b where a.name="t0") sysColumns) sql;
3)select * from TEMP.t1;
`

**Comment by twoxfh** [comment]
While I understand this request is a bit (a lot) "hackish' it really does provide some quick data analysis of query exploration. I was able to setup a statement_vtab to format a json object, another to format the scalar function queries, and finally one to execute. Will close issue unless something simpler can be achieved.

**Comment by 0x09** [comment]
@twoxfh that sounds similar to something I did early on with this extension, where implementing a user defined function to return rows from an input table as JSON in combination with the json1 extension allows one to create statement_vtabs that can flatten the given table or do other kinds of transformations.
Unfortunately I don't think it's possible to implement what you're looking for using virtual tables as the number of columns in the vtab would not be known at the time it's declared (which is a requirement of the engine), so if your solution using json is working that may really be the best way.

**Comment by twoxfh** [comment]
> @twoxfh that sounds similar to something I did early on with this extension, where implementing a user defined function to return rows from an input table as JSON in combination with the json1 extension allows one to create statement_vtabs that can flatten the given table or do other kinds of transformations.
> Unfortunately I don't think it's possible to implement what you're looking for using virtual tables as the number of columns in the vtab would not be known at the time it's declared (which is a requirement of the engine), so if your solution using json is working that may really be the best way.

@0x09 Thanks for your feedback. I failed to mention I also created an extension to get select query columns at runtime. The other problem I ran into is prepared statements don't like you changing the table names and eval only evaluates to one column hence the json.
