### ISSUE TITLE
Add license please

### ISSUE THREAD

**Issue by ddevienne** [0x09/sqlite-statement-vtab#4]
I'm reusing your fine extension, in proprietary code. Is that OK? There's no license, in the code or repo, thus I'm unsure.
Would you mind adding a license? Hopefully one that allows reuse in any context. Thanks, --DD

**Comment by 0x09** [comment]
Hi @ddevienne, the module includes a short disclaimer of copyright entirely patterned after SQLite's. The pull request linked above will supplement this with the full text of the [CC0 public domain declaration](https://creativecommons.org/publicdomain/zero/1.0/) for any contexts where a license is necessary. Although small, I would like the author of [this change](https://github.com/0x09/sqlite-statement-vtab/pull/3) to agree to that first.

To be clear the intent of using CC0/public domain here is simply for statement-vtab to be usable everywhere SQLite is without any additional restrictions.

**Comment by ddevienne** [comment]
Ah yes, sorry, I missed that sentence at the top of the file.
Having a license Github would pick-up and display on the left-hand-side would be nice.
Thanks for this very clever vtab. Cheers, --DD

```
 * In the interest of compatibility with SQLite's own license (or rather lack thereof),
 * the author disclaims copyright to this source code.
```
