### ISSUE TITLE
Export _init function on Windows

### ISSUE THREAD

**Issue by ddevienne** [0x09/sqlite-statement-vtab#6]
Just finished writing a unit test for SQLite's own eval.c and your nifty statement_vtab.c,
and dynamically loading yours failed on Windows, while eval was OK. As expected, the
difference was that yours does not export the `sqlite3_statementvtab_init()` function.

Would you mind adding it, please? Thanks, --DD
```
#ifdef _WIN32
__declspec(dllexport)
#endif
int sqlite3_statementvtab_init(sqlite3* db, char** pzErrMsg, const sqlite3_api_routines* pApi) {
    ...
}
```

**Comment by 0x09** [comment]
@ddevienne makes sense, thanks for finding this. Added in dab1c388dedaa92016a6e401e3919e40014f67e3
